# Generated by Django 5.0.1 on 2024-01-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('column_names', models.CharField(max_length=128)),
                ('row_names', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_skills', models.CharField(blank=True, max_length=512, null=True)),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('area_name', models.CharField(max_length=128)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.CharField(max_length=128)),
                ('value_b', models.CharField(max_length=128)),
                ('table_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tabledata')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='tabledata',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.theme'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images/')),
                ('alt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.theme')),
            ],
        ),
    ]
