# Generated by Django 5.0.1 on 2024-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_vacancy_avg_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='avg_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
